version: '3.1'

volumes:
  database:
  backend:
    
services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --authentication_policy=mysql_native_password
    restart: always
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d
      # - ./database/data:/var/lib/mysql
    env_file: db.env
    ports:
      - 3306:3306
    networks:
      - backend

  adminer-db:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080
    networks:
      - backend
  
  backend:
    image: flf/backend-dev
    build:
      context: backend
      dockerfile: Dockerfile
    user: "node"
    env_file: 
      - db.env
      - back.env
    entrypoint: ["sh", "-c"]
    command: ["yarn && yarn dev"]
    volumes:
      - ./backend:/home/node/app
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
  frontend: