exit: true
bail: true
slow: 1000
recursive: true
exclude:
  - "src/server.ts"
  - "src/Libs/Logger.ts"
  - "src/Libs/Morgan.ts"
  - "src/database/index.ts"
  - "src/routes/index.ts"
spec:
  - "tests/**/*.spec.ts"
