all: true
check-coverage: true
extension:
  - ".ts"
include:
  - "src/**/*.ts"
exclude:
  - "**/*.spec.ts"
  - "**/*.js"
  - "src/server.ts"
  - "src/Libs/Logger.ts"
  - "src/Libs/Morgan.ts"
  - "src/database/index.ts"
  - "src/routes/index.ts"
  - "src/config/*.ts"
  - "src/repositories/*.ts"
settings:
  lines: 100
  branches: 100
  functions: 100
  statements: 100
